name: pharmacyapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf

    - family: Poppins1
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf

    - family: FredokaLight
      fonts:
        - asset: fonts/fredoka-latin-400-normal.ttf


    - family: FredokaBold
      fonts:
        - asset: fonts/fredoka-latin-ext-700-normal.ttf